version: '3'
services:
  frontend:
    build:
      context: ./frontend/litter-box-web
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build:
      context: ./backend/LitterBox.Api/LitterBox.Api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - database
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kittycatmeow
      POSTGRES_DB: litter_box